version: '3.8'

services:
  db:
    container_name: kartoon
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=kartoonDB
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - kartoondata:/var/lib/postgresql/data

  app:
    build: .
    container_name: kartoon-app
    restart: always
    ports:
      - "8000:8000" # External:Internal port mapping
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/kartoonDB
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app

volumes:
  kartoondata:
